import { computeTargetZ, type ScrewSpotParams, type ScrewSpotPoint } from "./definitions";

interface GenerateArgs {
	points: ScrewSpotPoint[];
	params: ScrewSpotParams;
	units: "mm" | "in";
	// Homing-aware safe retract from getSafeRetractCode() (G53 when homing, else an
	// incremental G91 lift). Emitted to lift before the first move and to park at the
	// end; we re-assert G90 after it since that helper leaves the modal state to us.
	retractCode?: string[];
	returnArray?: boolean;
}

const fixed = (n: number): number => Number(n.toFixed(3));

/**
 * Greedy nearest-neighbour ordering to trim the rapid travel between holes. Seeded
 * from the work origin so the first hole is the one closest to it.
 */
export function orderPointsNearestNeighbour(
	points: ScrewSpotPoint[],
	start: ScrewSpotPoint = { x: 0, y: 0 },
): ScrewSpotPoint[] {
	const remaining = [...points];
	const ordered: ScrewSpotPoint[] = [];
	let cursor = start;

	while (remaining.length) {
		let best = 0;
		let bestDist = Infinity;
		for (let i = 0; i < remaining.length; i++) {
			const dx = remaining[i].x - cursor.x;
			const dy = remaining[i].y - cursor.y;
			const dist = dx * dx + dy * dy;
			if (dist < bestDist) {
				bestDist = dist;
				best = i;
			}
		}
		cursor = remaining[best];
		ordered.push(cursor);
		remaining.splice(best, 1);
	}

	return ordered;
}

/**
 * Build the spot-drilling program for the picked points. Pure — all machine/store
 * derived values are passed in so it stays trivially testable. Rapids run at an
 * absolute work-Z clearance above the top surface; each hole plunges to the computed
 * target Z at the plunge feed. Injected via controller.command("gcode", …) so the
 * user's loaded job is left untouched.
 */
export function generateScrewSpotGcode(args: GenerateArgs): string | string[] {
	const { points, params, units, retractCode = [], returnArray = false } = args;
	const { spindleRPM, spindleDwell, plungeFeedrate, retractHeight, auxOutput } = params;

	const clearanceZ = fixed(Math.abs(retractHeight));
	const targetZ = computeTargetZ(params);
	const ordered = orderPointsNearestNeighbour(points);

	const unitModal = units === "in" ? "G20 ;inches" : "G21 ;mm";
	const auxOn =
		auxOutput === "flood"
			? ["M8 ;Aux output on"]
			: auxOutput === "mist"
				? ["M7 ;Aux output on"]
				: [];
	const auxOff = auxOutput === "none" ? [] : ["M9 ;Aux output off"];
	const spinUp = spindleDwell > 0 ? [`G4 P${fixed(spindleDwell)} ;Spindle spin-up`] : [];

	const gcode: string[] = [
		"(Header)",
		"(Generated by gSender from Sienci Labs - Screw Spot)",
		unitModal,
		"G90",
		...auxOn,
		`M3 S${Math.round(spindleRPM)}`,
		...spinUp,
		...retractCode,
		"G90",
		"(Header End)",
		"",
	];

	ordered.forEach((pt, i) => {
		gcode.push(
			`(Spot ${i + 1})`,
			`G0 Z${clearanceZ}`,
			`G0 X${fixed(pt.x)} Y${fixed(pt.y)}`,
			`G1 Z${targetZ} F${Math.round(plungeFeedrate)}`,
			"",
		);
	});

	gcode.push(
		"(Footer)",
		`G0 Z${clearanceZ}`,
		...retractCode,
		"G90",
		"M5 ;Turn off spindle",
		...auxOff,
		"(End of Footer)",
	);

	return returnArray ? gcode : gcode.join("\n");
}
